### PR TITLE
autoconvert to NULL

### PR DESCRIPTION
**Pull request by mb706**
See https://github.com/mlr-org/mlr3pipelines/pull/451 and in particular [this comment and the following of mine](https://github.com/mlr-org/mlr3pipelines/pull/451#issuecomment-669523116).

If someone can add tests (e.g. from #451) and if @RaphaelS1 can confirm that this works for him this can be merged.

### CODE REVIEW

**Comment by RaphaelS1** [comment]
I will try and use this in a pipeline I have tomorrow that requires it and see if it works as expected for the use case.

**Comment by mb706** [comment]
Tests fail because we actually have an assertion somewhere about `Task %>>% NULL` failing. The test should probably be changed to something that actually still fails.

**Comment by RaphaelS1** [comment]
Thanks @mb706 works as expected, so basically as far as I'm concerned it's just like using a NOP but don't need to set 'phase' because it automatically converts to NULL?

**Comment by mb706** [comment]
@sumny could you write a test or two for this and adjust the broken test?

**Pull request merged**
