### PR TITLE
Style pkg

### PR DESCRIPTION
**Pull request by pat-s**
Applying `styler::mlr_style()`

### CODE REVIEW

**Comment by pat-s** [comment]
@mb706 	Can we merge this? Build errors are the same as in master.

**Comment by mb706** [comment]
Too many conflicts to merge; instead I adjusted things manually now. I left things I disagree with out (short `if ()` on one line, `on.error({})` on one line, two spaces before inline comment, cosmetic empty lines).

**Comment by pat-s** [comment]
The we should probably discuss the style guide again, otherwise we do not need one.

**Comment by berndbischl** [comment]
> The we should probably discuss the style guide again, otherwise we do not need one.

we will dicuss this in one of the next core meeting but @pat-s @mb706 @mllg must all be present

**Pull request closed without merging**
