### PR TITLE
allow PipeOpMutate to use new features on the fly

### LINKED ISSUE #424: PipeOpMutate does not allow to use just-created feature
mutation=list(disp_half =~ disp/2, disp_quart = ~disp_half/2))

produces following:

Error in eval(frm[[2]], envir = taskdata, enclos = environment(frm)) :   object 'disp_half' not found

===================
For the detailed example
po('mutate', mutation=list(disp_half =~ disp/2, disp_quart = ~disp_half/2))$train(list(tsk('mtcars')))[[1]]$data()

### PR DESCRIPTION
**Pull request by sumny**
closes #424 
Not sure if we actually want this. Works by evaluating the formulas sequentially in a for-loop and adding the variables to the temporary taskdata. May result in the need for users being more cautious when changing existing features.

### CODE REVIEW

**Comment by mb706** [comment]
```r
oldtask = copy(taskdata)
....
eval(..., envir = insert_named(as.list(taskdata), oldtask), enclos = environment(...))
```

**Comment by mb706** [comment]
also make a test that old data actually has preference before new data

**Comment by sumny** [comment]
> ```r
> oldtask = copy(taskdata)
> ....
> eval(..., envir = insert_named(as.list(taskdata), oldtask), enclos = environment(...))
> ```

nice!

**Comment by sumny** [comment]
> also make a test that old data actually has precedence before new data

done

**Pull request merged**
