### PR TITLE
PO Threshold

### PR DESCRIPTION
**Pull request by pfistfl**
PipeOp to set the threshold of a prediction.
Can be tuned from the outside.

### CODE REVIEW

**Comment by pfistfl** [comment]
This can be reviewed, ignore the stuff in `attic` for now, this will be required for `PipeOpTuneThreshold` later.

**Comment by mllg** [comment]
This just allows to set the threshold, right? Is there a way to tune the threshold without re-fitting the pipeline?

**Comment by mllg** [comment]
The pipeop should probably have these inputs/outputs?

```r
  input = data.table(name = "input", train = "NULL", predict = "PredictionClassif"),
  output = data.table(name = "output", train = "NULL", predict = "PredictionClassif")
```

**Comment by pfistfl** [comment]
Currently not, as the Leaner does not pass  anything onward during train.
If we change this, we could threshold tune the learner.

**Pull request merged**
