### PR TITLE
add PipeOpRenameColumns

### PR DESCRIPTION
**Pull request by sumny**
see also #420

### CODE REVIEW

**Comment by mb706** [comment]
one parameter: named character `renaming`. renames columns as found in *names* of `renaming`  to *values* of `renaming`.

**Comment by mb706** [comment]
maybe an extra flag, if we allow columns in the `renaming` vector that are not actually present in the task.

**Comment by sumny** [comment]
> one parameter: named character `renaming`. renames columns as found in _names_ of `renaming` to _values_ of `renaming`.

done!

**Comment by sumny** [comment]
> maybe an extra flag, if we allow columns in the `renaming` vector that are not actually present in the task.

This will nevertheless be checked when the `rename` mutator of the `Task` is being called, so I am not sure whether we need this.

**Pull request merged**
